# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stacc < Formula
  desc ""
  homepage "https://stacc.com/"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/stacc/stacc-CLI/releases/download/v0.1.0/stacc_0.1.0_Darwin_x86_64.tar.gz"
    sha256 "9dd43a3d0fdc6b1e718fad56c772863a00e437f4b63c2ab20bce5e8077aff3d0"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/stacc/stacc-CLI/releases/download/v0.1.0/stacc_0.1.0_Linux_x86_64.tar.gz"
    sha256 "0624dc77960737f5889c1d28026204a0b80b257bf7799127063a7974039a56ff"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/stacc/stacc-CLI/releases/download/v0.1.0/stacc_0.1.0_Linux_arm64.tar.gz"
    sha256 "05605309c666eae8f4505d2753ee39fca39184c1f2a825e9ad60bb84f3f4b0c2"
  end

  def install
    bin.install "stacc"
  end
end
