# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stacc < Formula
  desc "Software used to communicate with Stacc cloud environments."
  homepage "https://stacc.com/"
  version "0.1.0"
  license "Apache-2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/stacc/stacc-CLI/releases/download/v0.1.0/stacc_0.1.0_Darwin_x86_64.tar.gz"
    sha256 "37cd1c16b9e25d88261d54e107756dc9e539da6655e0b78ec3e77e1856ac3e63"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/stacc/stacc-CLI/releases/download/v0.1.0/stacc_0.1.0_Linux_x86_64.tar.gz"
    sha256 "87fa6fe26ce3c3dccc46f21846408249f9235f762b6d0181b46e80eca58356fe"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/stacc/stacc-CLI/releases/download/v0.1.0/stacc_0.1.0_Linux_arm64.tar.gz"
    sha256 "246a4b3e5d25a5266c6feff01c230a28cc69d1f41fdc2bb94feacd0602807d90"
  end

  def install
    bin.install "stacc"
  end
end
